### ISSUE TITLE
Error about dataset

### ISSUE THREAD

**Issue by KangdiSun** [zju3dv/hghoi#3]
When I was trying to train using command python train.py --config configs/goalpose/vqvae.yaml, I got error: No such file or directory: './datasets/samp/MotionWorld/train/Input.txt'. May I ask when will the missing datasets/files be posted?

**Comment by phj128** [comment]
You could export the data with Unity by yourself. You can also download our exported data following [this](https://github.com/zju3dv/hghoi/tree/main/python#exported-training-data-and-pretrained-models).
